[package]
name = "auto_check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
craftping = "0.4.1"
json = "0.12.4"
regex = "1.7.3"
serde = "1.0.160"
serde_derive = "1.0.160"
serde_json = "1.0.96"
